name: LBJ
favicon: null
layout_spectrum: 0.5525752070825547
typography_spectrum: 0.9594603995792568
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.16889731236733496
  lightness: 0.24748796271160245
  saturation: 0.15233726403675973
  rhythmicContrast: 0.5507814807351679
purpose: []
