cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.625448
  brandStrength: 0.168897312367335
  lightness: 0.6577061
  brandColors:
    - '#85A4C3'
    - '#C3D2D7'
    - '#ECA87B'
    - '#2E4E5B'
    - '#FDE26C'
  rhythmicContrast: 0.734767
typography_spectrum: 0.781362
layout_spectrum: 0.9175627
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: LBJ
