name: LBJ
favicon: null
layout_spectrum: 0.25555
typography_spectrum: 0.53702
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252523'
    - '#ffffff'
    - '#fbe037'
    - '#a46a45'
    - '#a82c36'
  brandStrength: 0.16889731236733496
  lightness: 0.4375
  saturation: 0.15233726403675973
  rhythmicContrast: 0.5507814807351679
purpose: []
